// Code generated by microwave. DO NOT EDIT.

//go:generate microwave ./... --out bbq.go --pkg bbq

package bbq

import (
	"github.com/kamjapowered/bbq/constraints"
	"github.com/kamjapowered/bbq/functional"
	"github.com/kamjapowered/bbq/geometry"
	"github.com/kamjapowered/bbq/hashmap"
	"github.com/kamjapowered/bbq/log"
	"github.com/kamjapowered/bbq/math"
	"github.com/kamjapowered/bbq/queue"
	"github.com/kamjapowered/bbq/set"
	"github.com/kamjapowered/bbq/sort"
	"github.com/kamjapowered/bbq/stack"
	"github.com/kamjapowered/bbq/system"
	"os"
	"reflect"
)

// ===========
// constraints
// ===========

type Float = constraints.Float

type Integer = constraints.Integer

type Number = constraints.Number

type Ordered = constraints.Ordered

type Signed = constraints.Signed

type Unsigned = constraints.Unsigned

// ==========
// functional
// ==========

func ApplyOptions[T any](v *T, opts ...Option[T]) { functional.ApplyOptions(v, opts...) }

type Option[T any] = functional.Option[T]

// ========
// geometry
// ========

// store an arrow for debug or drawing
type Arrow[T Number] = geometry.Arrow[T]

// store a capsule as a segment plus radius
type Capsule[T Number] = geometry.Capsule[T]

// store an ellipse in local space using radii
//
// interpret as 2d on the xy plane
type Ellipse[T Number] = geometry.Ellipse[T]

// store a line as a point plus direction vector
type Line[T Number] = geometry.Line[T]

// create an arrow
func NewArrow[T Number](start Vector[T], end Vector[T], headLength T, headWidth T) Arrow[T] {
	return geometry.NewArrow(start, end, headLength, headWidth)
}

// create a capsule
func NewCapsule[T Number](seg Segment[T], radius T) Capsule[T] {
	return geometry.NewCapsule(seg, radius)
}

// create a circle from radius
func NewCircle[T Number](r T) Ellipse[T] { return geometry.NewCircle(r) }

// create a circle from diameter
func NewCircleD[T Number](d T) Ellipse[T] { return geometry.NewCircleD(d) }

// create an ellipse from radii
func NewEllipse[T Number](rx T, ry T) Ellipse[T] { return geometry.NewEllipse(rx, ry) }

// create an ellipse from height and width
func NewEllipseHW[T Number](h T, w T) Ellipse[T] { return geometry.NewEllipseHW(h, w) }

// create a line from two points
func NewLine[T Number](p0 Vector[T], p1 Vector[T]) Line[T] { return geometry.NewLine(p0, p1) }

// create an empty path
func NewPath[T Number]() Path[T] { return geometry.NewPath[T]() }

// create an empty polygon
func NewPolygon[T Number]() Polygon[T] { return geometry.NewPolygon[T]() }

// create a ray from two points
func NewRay[T Number](origin Vector[T], through Vector[T]) Ray[T] {
	return geometry.NewRay(origin, through)
}

// create a rectangle size
func NewRect[T Number](w T, h T) Rect[T] { return geometry.NewRect(w, h) }

// create a segment from start and end
func NewSegment[T Number](start Vector[T], end Vector[T]) Segment[T] {
	return geometry.NewSegment(start, end)
}

// create a square size
func NewSquare[T Number](s T) Rect[T] { return geometry.NewSquare(s) }

// create a vector up until the specified dimension
func NewVector[T Number](v ...T) Vector[T] { return geometry.NewVector(v...) }

// store a path as ordered points in local space
//
// interpret as 2d on the xy plane
type Path[T Number] = geometry.Path[T]

// store a polygon as points in local space
//
// interpret as 2d on the xy plane
type Polygon[T Number] = geometry.Polygon[T]

// store a ray as origin plus direction vector
type Ray[T Number] = geometry.Ray[T]

// store a local axis aligned rectangle size
//
// interpret as 2d on the xy plane with center at origin
type Rect[T Number] = geometry.Rect[T]

// store a segment as start and end points
type Segment[T Number] = geometry.Segment[T]

// store a 3d vector where z can be left as zero for 2d usage
type Vector[T Number] = geometry.Vector[T]

// =======
// hashmap
// =======

// store a one to one mapping between keys and values
//
// putting an existing key replaces its value
// putting an existing value replaces its key
//
// this type is not safe for concurrent use
type BiHashmap[K, V comparable] = hashmap.BiHashmap[K, V]

// store values in a dense slice while providing O(1) lookup by key.
//
// this type is not safe for concurrent use.
type DenseMap[K comparable, V any] = hashmap.DenseMap[K, V]

// create an empty bimap
//
// time: O(1)
func NewBiHashmap[K, V comparable]() *BiHashmap[K, V] { return hashmap.NewBiHashmap[K, V]() }

// create an empty densemap.
//
// time: O(1)
func NewDenseMap[K comparable, V any]() *DenseMap[K, V] { return hashmap.NewDenseMap[K, V]() }

// create an empty typemap
func NewTypeMap() *TypeMap { return hashmap.NewTypeMap() }

// store values keyed by base reflect type
//
// store values as pointers to their base type to allow in place mutation
//
// allow at most one value per base type
type TypeMap = hashmap.TypeMap

// get retrieves the stored pointer for the base type T
//
// require T to be a non pointer type
//
// return false if the entry does not exist or the cast fails
func TypeMapGet[T any](tm *TypeMap) (*T, bool) { return hashmap.TypeMapGet[T](tm) }

// retrieves the stored pointer for the base type of t
func TypeMapGetByType(tm *TypeMap, t reflect.Type) (any, bool) {
	return hashmap.TypeMapGetByType(tm, t)
}

// checks the existance of T in the TypeMap
//
// require T to be a non pointer type
func TypeMapHas[T any](tm *TypeMap) bool { return hashmap.TypeMapHas[T](tm) }

// remove deletes the entry for the base type T
//
// require T to be a non pointer type
func TypeMapRemove[T any](tm *TypeMap) bool { return hashmap.TypeMapRemove[T](tm) }

// removes the entry keyed by the base type of t
func TypeMapRemoveByType(tm *TypeMap, t reflect.Type) bool { return hashmap.TypeMapRemoveByType(tm, t) }

// add stores v under the base type of T
//
// require T to be a non pointer type
//
// store the value as *T
func TypeMapSet[T any](tm *TypeMap, v T) bool { return hashmap.TypeMapSet(tm, v) }

// stores v under the base type of t
//
// accept v as either base value or pointer to base value
func TypeMapSetByType(tm *TypeMap, v any, t reflect.Type) bool {
	return hashmap.TypeMapSetByType(tm, v, t)
}

// ===
// log
// ===

// store structured metadata for a record
type Field = log.Field

// intended for development diagnostics
const LogDebug = log.LogDebug

// intended for failures that affect behaviour
const LogError = log.LogError

// intended for unrecoverable failures. it does not exit the process, it only records the message
const LogFatal = log.LogFatal

// store log records and forward them to sinks
//
// records are kept in fifo order up to the configured maximum
//
// this type is not safe for concurrent use
type Logger = log.Logger

// intended for high level engine or game state messages
const LogInfo = log.LogInfo

// the severity level used by the logger
type LogLevel = log.LogLevel

// the highest defined log level
const LogMaxLevel = log.LogMaxLevel

// provide option helpers for log records
var LogOpt = log.LogOpt

// intended for unexpected but recoverable situations
const LogWarning = log.LogWarning

// create a logger that keeps at most maxRecords records
//
// if maxRecords is less than or equal to zero, records are not retained
//
// time: O(n) due to allocation
func NewLogger(maxRecords int) *Logger { return log.NewLogger(maxRecords) }

// describe one log entry
type Record = log.Record

// ====
// math
// ====

// return the absolute value
//
// time: O(1)
func Abs[T Number](v T) T { return math.Abs(v) }

// report whether a and b are within eps
//
// time: O(1)
func AlmostEqual[T Float](a T, b T, eps T) bool { return math.AlmostEqual(a, b, eps) }

// clamp value to the inclusive range [lo, hi]
//
// if lo is greater than hi, it swaps them
//
// time: O(1)
func Clip[T Number](value T, lo T, hi T) T { return math.Clip(value, lo, hi) }

// return t such that lerp(a, b, t) equals v
//
// return 0 if a equals b
//
// time: O(1)
func InvLerp[T Float](a T, b T, v T) T { return math.InvLerp(a, b, v) }

// linearly interpolate from a to b using t
//
// time: O(1)
func Lerp[T Float](a T, b T, t T) T { return math.Lerp(a, b, t) }

// return the arithmetic mean of values
//
// return 0 if values is empty
//
// time: O(n)
func Mean[T Number](values []T) T { return math.Mean(values) }

// return the minimum and maximum value in values
//
// return 0, 0 if values is empty
//
// time: O(n)
func MinMax[T Number](values []T) (T, T) { return math.MinMax(values) }

// map v from [inMin, inMax] to [outMin, outMax]
//
// return outMin if inMin equals inMax
//
// time: O(1)
func Remap[T Float](v T, inMin T, inMax T, outMin T, outMax T) T {
	return math.Remap(v, inMin, inMax, outMin, outMax)
}

// return the sign of v as -1, 0, or 1
//
// time: O(1)
func Sign[T Signed](v T) T { return math.Sign(v) }

// return the sign of v as -1, 0, or 1
//
// time: O(1)
func SignFloat[T Float](v T) T { return math.SignFloat(v) }

// return the sum of values
//
// time: O(n)
func Sum[T Number](values []T) T { return math.Sum(values) }

// return the population variance of values
//
// return 0 if values is empty
//
// time: O(n)
func Variance[T Float](values []T) T { return math.Variance(values) }

// =====
// queue
// =====

// store up to a fixed number of elements in fifo order
//
// this type is not safe for concurrent use
type BoundedQueue[T any] = queue.BoundedQueue[T]

// store elements in a double ended fifo structure using a ring buffer
//
// this type is not safe for concurrent use
type Deque[T any] = queue.Deque[T]

// create a new fifo queue with a fixed capacity
//
// if capacity is less than or equal to zero, create an empty queue that rejects enqueues
//
// time: O(n) due to allocation
func NewBoundedQueue[T any](capacity int) *BoundedQueue[T] { return queue.NewBoundedQueue[T](capacity) }

// create an empty deque
//
// time: O(1)
func NewDeque[T any]() *Deque[T] { return queue.NewDeque[T]() }

// create an empty priority queue
//
// time: O(1)
func NewPriorityQueue[T any](less func(a, b T) bool) *PriorityQueue[T] {
	return queue.NewPriorityQueue(less)
}

// create an empty queue.
//
// time: O(1)
func NewQueue[T any]() *Queue[T] { return queue.NewQueue[T]() }

// create an empty ring backed queue with the given capacity
//
// if capacity is less than or equal to zero, the queue is created empty
// and will reject all enqueue operations
//
// time: O(n) due to allocation
func NewRingQueue[T any](capacity int) *RingQueue[T] { return queue.NewRingQueue[T](capacity) }

// store elements ordered by priority using a binary heap
//
// less(a, b) must return true if a has higher priority than b
//
// this type is not safe for concurrent use
type PriorityQueue[T any] = queue.PriorityQueue[T]

// store elements in fifo order using a ring buffer.
//
// this type is not safe for concurrent use.
type Queue[T any] = queue.Queue[T]

// store elements in fifo order using a fixed size ring buffer
//
// this type is not safe for concurrent use
type RingQueue[T any] = queue.RingQueue[T]

// ===
// set
// ===

// store membership of non negative integers using a bitset
//
// this type is not safe for concurrent use
type BitSet = set.BitSet

// track completion of a fixed set of required keys
//
// this type is not safe for concurrent use
type Checklist[K comparable] = set.Checklist[K]

// store unique elements using a hash table
//
// this type is not safe for concurrent use
type HashSet[T comparable] = set.HashSet[T]

// identify an element using an index and a generation.
//
// the high 32 bits store the generation and the low 32 bits store the index.
//
// the tag parameter gives nominal typing so ids from different domains do not
// mix (for example, entity and asset).
type Member[Tag any] = set.Member[Tag]

// create an empty bitset
//
// time: O(1)
func NewBitSet() *BitSet { return set.NewBitSet() }

// create a checklist with the given required keys
//
// time: O(n)
func NewChecklist[K comparable](required ...K) *Checklist[K] { return set.NewChecklist(required...) }

// create an empty set
//
// time: O(1)
func NewHashSet[T comparable]() *HashSet[T] { return set.NewHashSet[T]() }

// create an empty population.
//
// time: O(1)
func NewPopulation[Tag any]() *Population[Tag] { return set.NewPopulation[Tag]() }

// allocate and validate generational members.
//
// removed members become invalid and may be reused with a higher generation.
//
// member 0 is reserved and is never spawned. it does not live inside a
// population. this makes the zero value useful as an "unset" id.
//
// this type is not safe for concurrent use.
type Population[Tag any] = set.Population[Tag]

// ====
// sort
// ====

// describe a directed dependency from one node to another
//
// From must appear before To in a topological order
type Edge[T comparable] = sort.Edge[T]

// return a topological order for nodes
//
// nodes must not contain duplicates
// edges whose endpoints are not present in nodes are ignored
// duplicate edges are collapsed
// self edges are ignored
// return false if the graph contains a cycle
//
// time: O(n + e)
func TopoSort[T comparable](nodes []T, edges []Edge[T]) ([]T, bool) {
	return sort.TopoSort(nodes, edges)
}

// =====
// stack
// =====

// create an empty stack
//
// time: O(1)
func NewStack[T any]() *Stack[T] { return stack.NewStack[T]() }

// create an empty unique stack
//
// time: O(1)
func NewUniqueStack[T comparable]() *UniqueStack[T] { return stack.NewUniqueStack[T]() }

// store elements in lifo order using a slice as backing storage
//
// this type is not safe for concurrent use
type Stack[T any] = stack.Stack[T]

// store unique elements in lifo order
//
// pushing an existing element moves it to the top
//
// this type is not safe for concurrent use
type UniqueStack[T comparable] = stack.UniqueStack[T]

// ======
// system
// ======

// create a signal listener for the given signals
//
// if no signals are provided, it listens for sigint and sigterm
//
// time: O(1)
func NewSignalListener(signals ...os.Signal) *SignalListener {
	return system.NewSignalListener(signals...)
}

// listen for os signals and expose them through a channel
//
// this type is not safe for concurrent construction, but safe for concurrent use
type SignalListener = system.SignalListener
